name: ChaoticCore
main: me.chaoticmc.core.Core
version: 1.0.0
description: Custom core for ChaoticMC
authors: [nikitimeYO, IEDs, Synch]
depend: [Vault]
commands:
  help:
    description: Command help.
  gmc:
    description: Gamemode 1
    permission: chaoticmc.command.gamemode
    aliases: [gamemodec]
  gms:
    description: Gamemode 0
    permission: chaoticmc.command.gamemode
    aliases: [gamemodes]
  gm:
    description: Gamemode toggle
    permission: chaoticmc.command.gamemode
    aliases: [gamemode]
  fly:
    description: Flight mode
    permission: chaoticmc.command.fly
  v:
    description: Vanish toggle
    permission: chaoticmc.command.vanish
    aliases: [vanish]