name: ChaoticCore
main: me.chaoticmc.core.Core
version: 1.0.0
description: Custom core for ChaoticMC
authors: [nikitimeYO, IEDs, Synch]
depend: [Vault]
commands:
  help:
    description: Command help.
  gmc:
    description: Gamemode 1
    aliases: [gamemodec]
  gms:
    description: Gamemode 0
    aliases: [gamemodes]
  gm:
    description: Gamemode toggle
    aliases: [gamemode]
  fly:
    description: Flight mode
  god:
    description: God yourself
  v:
    description: Vanish toggle 
    aliases: [vanish]

